### ISSUE TITLE
Move under ISO TC 211 org namespace?

### ISSUE THREAD

**Issue by strogonoff** [ISO-TC211/jekyll-theme-isotc211-helpers#1]
We may want to move this under https://github.com/ISO-TC211/ so that it lives together with [theme gem](https://github.com/ISO-TC211/jekyll-theme-isotc211/).

**Comment by ronaldtse** [comment]
Agree!

**Comment by ronaldtse** [comment]
Done.

**Comment by strogonoff** [comment]
🎉
